### ISSUE TITLE
Unexpected tokens

### ISSUE THREAD

**Issue by rickvila** [khairul169/3rdperson-multiplayer#1]
Hi Khairul,

I'm using Win 10 64-bit and Godot_v2.1-stable_win64.exe.

There are a couple of errors found in gamestate.gd
```
error (119,0): Unexpected token: Identifier: master
error (126,0): Unexpected token: Identifier: master
error (154,0): Unexpected token: Identifier: remote
error (185,0): Unexpected token: Identifier: remote
error (191,0): Unexpected token: Identifier: sync
error (208,0): Unexpected token: Identifier: sync
Parser Error: Identifier not found: NetworkedMultiplayerENet (line 53)
```

Does the game work out of the box or do I have to install some external libraries/assets?

Regards,

Rick

**Comment by khairul169** [comment]
Hello, this project required the latest version of godot engine.
You may need to compile from the source ;)

**Comment by rickvila** [comment]
I guess this won't be fixed by those who don't know how to compile from source. The version I'm using was recently released see [godot-reaches-2-1-stable](https://godotengine.org/article/godot-reaches-2-1-stable). Please help me understand your code instead. Where specifically in the documentation that the tokens (master, remote and sync) are mentioned?

**Comment by khairul169** [comment]
http://docs.godotengine.org/en/latest/tutorials/high_level_multiplayer.html ;)

**Comment by hugoarbones** [comment]
Mine still won't work. Neither the "master" or the GDNetAddress please help
